healthcare_dbt_bigquery_data_pipeline:
  target: dev
  outputs:
      dev:
        dataset: dev_healthcare_data
        job_execution_timeout_seconds: 300
        job_retries: 1
        keyfile: '/mnt/c/Users/teffm/Documents/PROGRAMMING/DATA_ENGINEERING/healthcare-data-project-482216-cb3af346ad83.json'
        location: europe-west1
        method: service-account
        priority: interactive
        project: healthcare-data-project-482216
        threads: 4
        type: bigquery
      prod:
        dataset: prod_healthcare_data
        job_execution_timeout_seconds: 300
        job_retries: 1
        keyfile: '/mnt/c/Users/teffm/Documents/PROGRAMMING/DATA_ENGINEERING/healthcare-data-project-482216-cb3af346ad83.json'
        location: europe-west1
        method: service-account
        priority: interactive
        project: healthcare-data-project-482216
        threads: 4
        type: bigquery
